### ISSUE TITLE
License not specified

### ISSUE THREAD

**Issue by jareks** [futpib/eslint-template-visitor#23]
It seems that license for this project is not fully specified. 

Could you please include selected license in the code? From my understanding of package.json the intention is dual licensing MIT / GPL. That seems a bit superfluous as only MIT license seems to have same practial result?

**Comment by futpib** [comment]
As I understand it, if someone intended to fork a dual-licensed GPL / MIT project and turn it into a GPL project they could do it (legally) without any issue. If they were to fork a pure MIT licensed project and turn it into a GPL project they would not be able to do it (legally). This license choice was not thought through though. If you face any trouble with this choice of licenses or if this stops you from contributing, please elaborate and I will reconsider licenses. Otherwise I don't see what's the issue here.

**Comment by jareks** [comment]
Thanks for quick reply :-) 
Your choice of dual licenses is of course fine albeit uncommon and that's not an issue here.

The issue here is that there are no LICENSE files in the repository. Please take a look at: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
